- include: meta/defaults.yaml

- ifposix:
  - config:
    - link:
        ~/.lesskey: files/lesskey
    - shell:
      - command: |
          if command -v lesskey >/dev/null; then
            VERSION=$(lesskey -V | grep -Eo '[0-9]+$')
            [ "${VERSION}" -ge 582 ] || lesskey
          fi
        description: Compiling lesskey (deprecated)
