" gvimrc - GUI-specific vim configuration

" Default Options
set guicursor=a:block-blinkon0
set guioptions=eimg
set guitablabel=%N\ %t\ %m

" Fonts
if has('gui_gtk')
  set guifont=Droid\ Sans\ Mono\ for\ Powerline\ 11
elseif has('gui_macvim')
  set guifont=Droid\ Sans\ Mono\ for\ Powerline:h14
elseif has('gui_win32')
  set guifont=Droid\ Sans\ Mono\ for\ Powerline:h10
endif

" Enable pedantic colors when not using macOS:
if !has('gui_macvim')
  let g:wtf_pedantic_guicolors = 1
endif
