# zshrc - zsh configuration

bindkey -v
bindkey "^?" backward-delete-char
bindkey "^H" backward-delete-char

limit coredumpsize unlimited

# Disable flow control and freeze terminal settings:
stty -ixon
ttyctl -f

setopt NO_ALWAYS_LAST_PROMPT
setopt NO_AUTO_REMOVE_SLASH
setopt NO_HIST_BEEP
setopt NO_LIST_BEEP
setopt NO_PROMPT_SP

setopt AUTO_PUSHD
setopt COMPLETE_ALIASES
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_DUPS
setopt INC_APPEND_HISTORY
setopt MAGIC_EQUAL_SUBST
setopt NULL_GLOB
setopt PUSHD_IGNORE_DUPS
setopt RM_STAR_SILENT

export EDITOR=vim
export PAGER=less

# Rather than clutter zshrc, we source configuration from zshrc.d to
# further customize the shell:
for file in $HOME/.zshrc.d/*; do
	source $file
done

# vim: ft=zsh
